apiVersion: dip.io/v1alpha1
kind: Postgres
metadata:
  name: myapp-local-db
  namespace: default
spec:
  writeConnectionSecretToRef:
    name: myapp-local-db-secret
  compositionSelector:
    matchLabels:
      provider: cnpg
  database:
    # Generic sizing
    size: small
    
    # Standard configuration
    identifier: myapp-local
    databaseName: app
    engineVersion: "18.1"
    masterUsername: appuser
    masterPasswordSecretRef:
      name: myapp-db-secret
      key: password
    
    allocatedStorage: 20
    
    # HA
    multiAz: false
