apiVersion: dip.io/v1alpha1
kind: Postgres
metadata:
  name: myapp-db-access
  namespace: myapp
spec:
  
  # Database configuration - using existing RDS instance
  parameters:
    existingIdentifier: myapp-production-db
    type: rds-instance
    engine: postgres
    databaseName: application
    port: 5432
  

  
  # Tags for IAM resources
  tags:
    Application: myapp
    Environment: production
    Team: platform
