apiVersion: dip.io/v1alpha1
kind: Postgres
metadata:
  name: myapp-db-with-secret
  namespace: myapp
spec:
  
  # Database configuration - using existing RDS instance
  parameters:
    existingIdentifier: myapp-production-db
    type: rds-instance
    engine: postgres
    databaseName: application
    # Optional: provide resource ID directly if known
    resourceId: db-ABCDEFGHIJKLMNOP123456
  

  
  # Write connection details to a secret
  writeConnectionSecretToRef:
    name: myapp-db-credentials
  
  # Tags for IAM resources
  tags:
    Application: myapp
    Environment: production
    Team: platform
