apiVersion: dip.io/v1alpha1
kind: Postgres
metadata:
  name: myapp-minimal-db
  namespace: default
spec:
  database:
    identifier: myapp-minimal-db
    engineVersion: "18.1"
    
    masterUsername: postgres
    masterPasswordSecretRef:
      name: myapp-db-password
      
    provider: aws
    size: small
    allocatedStorage: 20
