apiVersion: dip.io/v1alpha1
kind: S3IRSA
metadata:
  name: my-app-storage-with-secret
  namespace: my-app
spec:
  # ServiceAccount configuration for IRSA binding
  serviceAccount:
    name: my-app-sa
  
  # Create a new S3 bucket with custom configuration
  parameters:
    name: my-app-data-bucket
    versioning: false
    encryption:
      enabled: true
  
  # IAM permissions
  permissions:
    allowRead: true
    allowWrite: true
  
  # Write connection details to a Kubernetes secret (in the same namespace)
  writeConnectionSecretToRef:
    name: my-app-s3-credentials
  
  # Tags for AWS resources
  tags:
    Application: my-app
    Environment: production
    Team: platform
