apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: postgres-cnpg
  namespace: crossplane-system
  labels:
    provider: cnpg
    revision: "47"
spec:
  # Reference to the XRD
  compositeTypeRef:
    apiVersion: dip.io/v1alpha1
    kind: Postgres
  
  mode: Pipeline
  
  pipeline:
  # Render CNPG resources
  - step: render-resources
    functionRef:
      name: function-go-templating
    input:
      apiVersion: gotemplating.fn.crossplane.io/v1beta1
      kind: GoTemplate
      source: Inline
      inline:
        template: |
          {{- $xr := .observed.composite.resource }}
          {{- $namespace := $xr.metadata.namespace }}
          {{- $name := $xr.metadata.name }}
          
          {{- /* T-Shirt Sizing Map */ -}}
          {{- $size := $xr.spec.parameters.size | default "small" }}
          
          {{- /* Restore Configuration */ -}}
          {{- $restoreIdentifier := "" }}
          {{- if $xr.spec.parameters.restore }}
            {{- $restoreIdentifier = $xr.spec.parameters.restore.sourceIdentifier }}
          {{- end }}
          
          {{- /* Identifier logic */ -}}
          {{- $targetIdentifier := $xr.spec.parameters.identifier | default "" }}
          
          {{- $dbAllocatedStorage := $xr.spec.parameters.allocatedStorage | default 20 }}
          {{- $dbStorageType := $xr.spec.parameters.storageType | default "gp3" }}
          {{- $dbMultiAz := $xr.spec.parameters.multiAz | default false }}
          {{- $databaseName := $xr.spec.parameters.databaseName | default "" }}


          {{- $dbMasterUsername := $xr.spec.parameters.masterUsername | default "" }}
          
          {{- /* Password Handling */ -}}
          {{- $dbMasterPasswordSecretName := "" }}
          {{- $dbMasterPasswordSecretKey := "password" }}
          {{- $generatedPassword := "" }}

          {{- if $xr.spec.parameters.masterPasswordSecretRef }}
             {{- $dbMasterPasswordSecretName = $xr.spec.parameters.masterPasswordSecretRef.name }}
             {{- $dbMasterPasswordSecretKey = $xr.spec.parameters.masterPasswordSecretRef.key | default "password" }}
          {{- else }}
             {{- $dbMasterPasswordSecretName = printf "%s-password" $name }}
             {{- /* Check if secret already exists to preserve password */ -}}
             {{- $observedResources := .observed.resources | default dict }}
             {{- $existingSecret := index $observedResources "password-secret" }}
             {{- if $existingSecret }}
               {{- $generatedPassword = index $existingSecret.resource.data "password" | b64dec }}
             {{- else }}
               {{- $generatedPassword = randAlphaNum 24 }}
             {{- end }}
          {{ end }} 
          
          {{- $dbMasterPasswordSecret := dict "name" $dbMasterPasswordSecretName "key" $dbMasterPasswordSecretKey }}
          {{- $dbPort := $xr.spec.parameters.port | default 5432 }}

          {{- /* Secret Name Logic - Always created */ -}}
          {{- $secretName := printf "%s-connection" $name }}
          {{- if $xr.spec.writeConnectionSecretToRef }}
            {{- $secretName = $xr.spec.writeConnectionSecretToRef.name }}
          {{- end }}
          
          {{- /* CNPG Resource Calculation */ -}}
          {{- $cnpgCpuReq := "500m" }}
          {{- $cnpgCpuLim := "1000m" }}
          {{- $cnpgMemReq := "512Mi" }}
          {{- $cnpgMemLim := "1Gi" }}
          {{- if eq $size "medium" }}
            {{- $cnpgCpuReq = "2" }}
            {{- $cnpgCpuLim = "2" }}
            {{- $cnpgMemReq = "4Gi" }}
            {{- $cnpgMemLim = "4Gi" }}
          {{- else if eq $size "large" }}
            {{- $cnpgCpuReq = "4" }}
            {{- $cnpgCpuLim = "4" }}
            {{- $cnpgMemReq = "16Gi" }}
            {{- $cnpgMemLim = "16Gi" }}
          {{- end }}
          
          {{- $cnpgInstances := 2 }}
          {{- if $dbMultiAz }}
            {{- $cnpgInstances = 3 }}
          {{- end }}
          
          {{- /* Map AWS storage types to K8s StorageClasses (simplistic mapping) */ -}}
          {{- $cnpgStorageClass := "standard" }}
          {{- if eq $dbStorageType "gp3" }}
             {{- $cnpgStorageClass = "gp3-encrypted" }}
          {{- end }}
          {{- if eq $dbStorageType "io1" }}
             {{- $cnpgStorageClass = "io1" }}
          {{- end }}
          
          ---
          apiVersion: postgresql.cnpg.io/v1
          kind: Cluster
          metadata:
            name: {{ $targetIdentifier }}
            namespace: {{ $namespace }}
            annotations:
              gotemplating.fn.crossplane.io/composition-resource-name: database
              crossplane.io/composition-resource-name: database
              crossplane.io/external-name: {{ $targetIdentifier }}
          spec:
            instances: {{ $cnpgInstances }}
            
            # Bootstrap configuration
            bootstrap:
              {{- if $restoreIdentifier }}
              recovery:
                backup:
                  name: {{ $restoreIdentifier }}
              {{- else }}
              initdb:
                database: {{ $databaseName | default "app" }}
                owner: {{ $dbMasterUsername | default "app" }}
                secret:
                  name: {{ $dbMasterPasswordSecret.name }}
              {{- end }}
            
            enableSuperuserAccess: true
            
            # Storage configuration
            storage:
              size: {{ $dbAllocatedStorage }}Gi
              storageClass: {{ $cnpgStorageClass }}
            
            # Resource Requirements
            resources:
              requests:
                memory: {{ $cnpgMemReq }}
                cpu: {{ $cnpgCpuReq }}
              limits:
                memory: {{ $cnpgMemLim }}
                cpu: {{ $cnpgCpuLim }}
          
          {{- /* Password Secret - Always created (stub if user provided) */ -}}
          {{- $pwSecretName := printf "%s-password" $name }}
          {{- if $xr.spec.parameters.masterPasswordSecretRef }}
             {{- $pwSecretName = printf "%s-password-stub" $name }}
          {{- end }}

          ---
          apiVersion: v1
          kind: Secret
          metadata:
            name: {{ $pwSecretName }}
            namespace: {{ $namespace }}
            annotations:
              gotemplating.fn.crossplane.io/composition-resource-name: password-secret
          type: Opaque
          data:
             {{- if not $xr.spec.parameters.masterPasswordSecretRef }}
             username: {{ $dbMasterUsername | default "app" | b64enc }}
             password: {{ $generatedPassword | b64enc }}
             {{- else }}
             stub: {{ "true" | b64enc }}
             {{- end }}
          

          
          {{- $fqdn := printf "%s-rw.%s.svc" $targetIdentifier $namespace }}
          
          ---
          # Superuser Secret (Required for postgres user consistency)
          apiVersion: v1
          kind: Secret
          metadata:
            name: {{ $targetIdentifier }}-superuser
            namespace: {{ $namespace }}
            annotations:
              gotemplating.fn.crossplane.io/composition-resource-name: superuser-secret
              cnpg.io/userType: superuser
              cnpg.io/cluster: {{ $targetIdentifier }}
          type: kubernetes.io/basic-auth
          data:
             username: {{ "postgres" | b64enc }}
             {{- if not $xr.spec.parameters.masterPasswordSecretRef }}
             password: {{ $generatedPassword | b64enc }}
             {{- else }}
             stub: {{ "true" | b64enc }}
             {{- end }}

          ---
          apiVersion: v1
          kind: Secret
          metadata:
            name: {{ $secretName }}
            namespace: {{ $namespace }}
            annotations:
              gotemplating.fn.crossplane.io/composition-resource-name: connection-secret
          type: Opaque
          data:
            endpoint: {{ printf "%s:%d" $fqdn (int $dbPort) | b64enc }}
            host: {{ $fqdn | b64enc }}
            port: {{ printf "%d" (int $dbPort) | b64enc }}
            username: {{ $dbMasterUsername | default "app" | b64enc }}
            database: {{ $databaseName | default "app" | b64enc }}
            sslmode: {{ "require" | b64enc }}
            {{- if $generatedPassword }}
            password: {{ $generatedPassword | b64enc }}
            {{- end }}
  
  # Patch status fields
  - step: patch-and-transform
    functionRef:
      name: function-patch-and-transform
    input:
      apiVersion: pt.fn.crossplane.io/v1beta1
      kind: Resources
      resources:
      - name: database
        patches:
        - type: ToCompositeFieldPath
          fromFieldPath: metadata.name
          toFieldPath: status.dbInstanceIdentifier
        - type: ToCompositeFieldPath
          fromFieldPath: status.writeService
          toFieldPath: status.dbEndpoint
        readinessChecks:
        # CNPG Readiness
        - fieldPath: status.phase
          matchString: "Cluster in healthy state"
          type: MatchString
      
      - name: password-secret
        readinessChecks:
        - type: MatchString
          fieldPath: kind
          matchString: Secret

      - name: connection-secret
        readinessChecks:
        - type: MatchString
          fieldPath: kind
          matchString: Secret

      - name: superuser-secret
        readinessChecks:
        - type: MatchString
          fieldPath: kind
          matchString: Secret
                
        # Secret Readiness (Always Ready)

  
  # Auto-ready function
  - step: auto-ready
    functionRef:
      name: function-auto-ready
