apiVersion: dip.io/v1alpha1
kind: HelmApplication
metadata:
  name: syncpolicy-custom-automated
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: "default"
  source:
    repoURL: "oci://ghcr.io/loafoe/helm-charts/go-hello-world"
    targetRevision: "0.15.0"
    helm:
      valuesObject:
        replicaCount: 1
  # Custom automated sync settings
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      allowEmpty: true
      enabled: false
