apiVersion: dip.io/v1alpha1
kind: HelmApplication
metadata:
  name: syncpolicy-with-ns-metadata
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: "default"
  source:
    repoURL: "oci://ghcr.io/loafoe/helm-charts/go-hello-world"
    targetRevision: "0.15.0"
    helm:
      valuesObject:
        replicaCount: 1
  # Sync policy with managed namespace metadata
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        team: platform
        environment: production
        managed-by: crossplane
      annotations:
        contact: platform-team@example.com
        description: "Managed by Crossplane HelmApplication"
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
