apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: helmapplications.dip.io
spec:
  group: dip.io
  names:
    kind: HelmApplication
    plural: helmapplications
  # Namespace scope - compositions will be namespace-scoped
  scope: Namespaced
  
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              # Source specification (matches ArgoCD Application spec.source)
              source:
                type: object
                description: "Source specification for the Helm chart"
                properties:
                  # Chart name (e.g., "my-chart")
                  chartName:
                    type: string
                    description: "Name of the Helm chart to deploy"
                  
                  # Chart repository URL
                  repoURL:
                    type: string
                    description: "URL of the Helm chart repository"
                  
                  # Chart version/revision
                  targetRevision:
                    type: string
                    description: "Target revision (version) of the Helm chart"
                  
                  # Optional path within the repository
                  path:
                    type: string
                    description: "Optional path to the chart within the repository"
                  
                  # Helm configuration
                  helm:
                    type: object
                    description: "Helm configuration"
                    properties:
                      # Helm release name
                      releaseName:
                        type: string
                        description: "Helm release name (defaults to the HelmApplication resource name)"
                      # Helm values as an object
                      valuesObject:
                        type: object
                        description: "Helm chart values as key-value pairs"
                        x-kubernetes-preserve-unknown-fields: true
                  
                  # Optional array of prefixes to filter environmentConfigs
                  withConfigKeys:
                    type: array
                    description: "Optional array of string prefixes to filter which environmentConfigs to include. If empty or not provided, all environmentConfigs are included."
                    items:
                      type: string
                
                required:
                - repoURL
                - targetRevision
              
              # ArgoCD project name
              project:
                type: string
                description: "ArgoCD project name (defaults to 'default')"
                default: "default"
            
            required:
            - source
          
          status:
            type: object
            properties:
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    status:
                      type: string
                    lastTransitionTime:
                      type: string
                    reason:
                      type: string
                    message:
                      type: string
